[package]
name = "app_server"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
rusqlite = {workspace=true}
serde = {workspace=true}
tokio = {workspace=true}
toml = {workspace=true}
shared_components = {path="../shared_components"}
